//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MizbanWS
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://microsoft.com/webservices/", ConfigurationName="MizbanWS.WSSMSSoap")]
    public interface WSSMSSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/GeSMSNumber", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<MizbanWS.GeSMSNumberResponse> GeSMSNumberAsync(MizbanWS.GeSMSNumberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/GetMessageStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> GetMessageStatusAsync(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/GetMessageStatuses21", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string[]> GetMessageStatuses21Async(long[] id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/GetMessageStatuses50004", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string[]> GetMessageStatuses50004Async(long[] id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/GetMessageStatuses", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int[]> GetMessageStatusesAsync(long[] id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/GetPreNum", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string[]> GetPreNumAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/GetPreNum5000", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string[]> GetPreNum5000Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/GetFreeNum", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<MizbanWS.GetFreeNumResponse> GetFreeNumAsync(MizbanWS.GetFreeNumRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/GetFreeNum5000", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<MizbanWS.GetFreeNum5000Response> GetFreeNum5000Async(MizbanWS.GetFreeNum5000Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/GePackage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<MizbanWS.GePackageResponse> GePackageAsync(MizbanWS.GePackageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/sendsmsSimCard", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<long[]> sendsmsSimCardAsync(string username, string password, string to, string text, string from, string api);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/sendsms2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<long[]> sendsms2Async(string username, string password, string to, string text, string from);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/sendsms", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<long[]> sendsmsAsync(string username, string password, string to, string text, string from, string api);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/Delsendsmsfuture", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<long[]> DelsendsmsfutureAsync(string username, string password, string Guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/sendsmsfuture", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<long[]> sendsmsfutureAsync(string username, string password, string to, string text, string from, string api, int year, int month, int day, int hour, int min);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/NazirSend", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<long[]> NazirSendAsync(string username, string password, string tobank, string text, string from, string api, int year, int month, int day, int hour, int min);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/smscounter", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> smscounterAsync(string text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/Credites", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<double> CreditesAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/GetAllMessageArray", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<MizbanWS.GetAllMessageArrayResponse> GetAllMessageArrayAsync(MizbanWS.GetAllMessageArrayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/GetBankId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> GetBankIdAsync(int bankId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/GetCountSms", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> GetCountSmsAsync(int bankId, int gender, int receiverNumberKind, int ageStart, int ageEnd, int receiverNumberPrefix);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/SendBulkSms", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> SendBulkSmsAsync(string username, string password, string api, string from, int bankId, string body, string recordEnd, int gender, int receiverNumberKind, int ageStart, int ageEnd, string title, int receiverNumberPrefix, string recordStart);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/GetAllMessage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<MizbanWS.GetAllMessageResponseGetAllMessageResult> GetAllMessageAsync(string username, string password, int countMsg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/GetUserExp", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<MizbanWS.GetUserExpResponse> GetUserExpAsync(MizbanWS.GetUserExpRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/GetUserContact", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<MizbanWS.GetUserContactResponseGetUserContactResult> GetUserContactAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/GetUserContactArray", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<MizbanWS.GetUserContactArrayResponse> GetUserContactArrayAsync(MizbanWS.GetUserContactArrayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/GetUserNumberArray", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<MizbanWS.GetUserNumberArrayResponse> GetUserNumberArrayAsync(MizbanWS.GetUserNumberArrayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/Logins2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<long[]> Logins2Async(string user, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/Logins", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<long[]> LoginsAsync(MizbanWS.NetworkCredential secuity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/GetState", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<MizbanWS.GetStateResponse> GetStateAsync(MizbanWS.GetStateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/GetCities", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<MizbanWS.GetCitiesResponse> GetCitiesAsync(MizbanWS.GetCitiesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/GetAllSendSmsArray", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<MizbanWS.GetAllSendSmsArrayResponse> GetAllSendSmsArrayAsync(MizbanWS.GetAllSendSmsArrayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/GetVerAndroid", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<MizbanWS.GetVerAndroidResponse> GetVerAndroidAsync(MizbanWS.GetVerAndroidRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/sendsmsGuid", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<long[]> sendsmsGuidAsync(string username, string password, string to, string text, string from, string api, string Guid);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class QuerySMSNumber
    {
        
        private string nameField;
        
        private string numberField;
        
        private string apiField;
        
        private string enableField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string api
        {
            get
            {
                return this.apiField;
            }
            set
            {
                this.apiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string enable
        {
            get
            {
                return this.enableField;
            }
            set
            {
                this.enableField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class VerAndroid
    {
        
        private string valueField;
        
        private string textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class SendMsgUser
    {
        
        private string mobileField;
        
        private string txtField;
        
        private string fromField;
        
        private string dateField;
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string mobile
        {
            get
            {
                return this.mobileField;
            }
            set
            {
                this.mobileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string txt
        {
            get
            {
                return this.txtField;
            }
            set
            {
                this.txtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string from
        {
            get
            {
                return this.fromField;
            }
            set
            {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class Cities
    {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class States
    {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class SecureString
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class NetworkCredential
    {
        
        private string userNameField;
        
        private string passwordField;
        
        private SecureString securePasswordField;
        
        private string domainField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public SecureString SecurePassword
        {
            get
            {
                return this.securePasswordField;
            }
            set
            {
                this.securePasswordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Domain
        {
            get
            {
                return this.domainField;
            }
            set
            {
                this.domainField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class SeUser
    {
        
        private string numberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class ContactUser
    {
        
        private string contactnameField;
        
        private string contactTelsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Contactname
        {
            get
            {
                return this.contactnameField;
            }
            set
            {
                this.contactnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ContactTels
        {
            get
            {
                return this.contactTelsField;
            }
            set
            {
                this.contactTelsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class expireUser
    {
        
        private string startdateField;
        
        private string enddateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string startdate
        {
            get
            {
                return this.startdateField;
            }
            set
            {
                this.startdateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string enddate
        {
            get
            {
                return this.enddateField;
            }
            set
            {
                this.enddateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class RecMsgUser
    {
        
        private string mobileField;
        
        private string txtField;
        
        private string fromField;
        
        private string dateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string mobile
        {
            get
            {
                return this.mobileField;
            }
            set
            {
                this.mobileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string txt
        {
            get
            {
                return this.txtField;
            }
            set
            {
                this.txtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string from
        {
            get
            {
                return this.fromField;
            }
            set
            {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class QueryPackage
    {
        
        private string nameField;
        
        private string priceField;
        
        private string minSaleField;
        
        private string tariffField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Price
        {
            get
            {
                return this.priceField;
            }
            set
            {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MinSale
        {
            get
            {
                return this.minSaleField;
            }
            set
            {
                this.minSaleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string tariff
        {
            get
            {
                return this.tariffField;
            }
            set
            {
                this.tariffField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class QueryNum5000
    {
        
        private bool openField;
        
        private string kindField;
        
        private int statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool open
        {
            get
            {
                return this.openField;
            }
            set
            {
                this.openField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string kind
        {
            get
            {
                return this.kindField;
            }
            set
            {
                this.kindField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class QueryNum
    {
        
        private bool openField;
        
        private string kindField;
        
        private int statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool open
        {
            get
            {
                return this.openField;
            }
            set
            {
                this.openField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string kind
        {
            get
            {
                return this.kindField;
            }
            set
            {
                this.kindField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GeSMSNumber", WrapperNamespace="http://microsoft.com/webservices/", IsWrapped=true)]
    public partial class GeSMSNumberRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://microsoft.com/webservices/", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://microsoft.com/webservices/", Order=1)]
        public string password;
        
        public GeSMSNumberRequest()
        {
        }
        
        public GeSMSNumberRequest(string username, string password)
        {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GeSMSNumberResponse", WrapperNamespace="http://microsoft.com/webservices/", IsWrapped=true)]
    public partial class GeSMSNumberResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://microsoft.com/webservices/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public MizbanWS.QuerySMSNumber[] GeSMSNumberResult;
        
        public GeSMSNumberResponse()
        {
        }
        
        public GeSMSNumberResponse(MizbanWS.QuerySMSNumber[] GeSMSNumberResult)
        {
            this.GeSMSNumberResult = GeSMSNumberResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFreeNum", WrapperNamespace="http://microsoft.com/webservices/", IsWrapped=true)]
    public partial class GetFreeNumRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://microsoft.com/webservices/", Order=0)]
        public string num;
        
        public GetFreeNumRequest()
        {
        }
        
        public GetFreeNumRequest(string num)
        {
            this.num = num;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFreeNumResponse", WrapperNamespace="http://microsoft.com/webservices/", IsWrapped=true)]
    public partial class GetFreeNumResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://microsoft.com/webservices/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public MizbanWS.QueryNum[] GetFreeNumResult;
        
        public GetFreeNumResponse()
        {
        }
        
        public GetFreeNumResponse(MizbanWS.QueryNum[] GetFreeNumResult)
        {
            this.GetFreeNumResult = GetFreeNumResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFreeNum5000", WrapperNamespace="http://microsoft.com/webservices/", IsWrapped=true)]
    public partial class GetFreeNum5000Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://microsoft.com/webservices/", Order=0)]
        public string num;
        
        public GetFreeNum5000Request()
        {
        }
        
        public GetFreeNum5000Request(string num)
        {
            this.num = num;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFreeNum5000Response", WrapperNamespace="http://microsoft.com/webservices/", IsWrapped=true)]
    public partial class GetFreeNum5000Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://microsoft.com/webservices/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public MizbanWS.QueryNum5000[] GetFreeNum5000Result;
        
        public GetFreeNum5000Response()
        {
        }
        
        public GetFreeNum5000Response(MizbanWS.QueryNum5000[] GetFreeNum5000Result)
        {
            this.GetFreeNum5000Result = GetFreeNum5000Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GePackage", WrapperNamespace="http://microsoft.com/webservices/", IsWrapped=true)]
    public partial class GePackageRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://microsoft.com/webservices/", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://microsoft.com/webservices/", Order=1)]
        public string password;
        
        public GePackageRequest()
        {
        }
        
        public GePackageRequest(string username, string password)
        {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GePackageResponse", WrapperNamespace="http://microsoft.com/webservices/", IsWrapped=true)]
    public partial class GePackageResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://microsoft.com/webservices/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public MizbanWS.QueryPackage[] GePackageResult;
        
        public GePackageResponse()
        {
        }
        
        public GePackageResponse(MizbanWS.QueryPackage[] GePackageResult)
        {
            this.GePackageResult = GePackageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllMessageArray", WrapperNamespace="http://microsoft.com/webservices/", IsWrapped=true)]
    public partial class GetAllMessageArrayRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://microsoft.com/webservices/", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://microsoft.com/webservices/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://microsoft.com/webservices/", Order=2)]
        public int countMsg;
        
        public GetAllMessageArrayRequest()
        {
        }
        
        public GetAllMessageArrayRequest(string username, string password, int countMsg)
        {
            this.username = username;
            this.password = password;
            this.countMsg = countMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllMessageArrayResponse", WrapperNamespace="http://microsoft.com/webservices/", IsWrapped=true)]
    public partial class GetAllMessageArrayResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://microsoft.com/webservices/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public MizbanWS.RecMsgUser[] GetAllMessageArrayResult;
        
        public GetAllMessageArrayResponse()
        {
        }
        
        public GetAllMessageArrayResponse(MizbanWS.RecMsgUser[] GetAllMessageArrayResult)
        {
            this.GetAllMessageArrayResult = GetAllMessageArrayResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://microsoft.com/webservices/")]
    public partial class GetAllMessageResponseGetAllMessageResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserExp", WrapperNamespace="http://microsoft.com/webservices/", IsWrapped=true)]
    public partial class GetUserExpRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://microsoft.com/webservices/", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://microsoft.com/webservices/", Order=1)]
        public string password;
        
        public GetUserExpRequest()
        {
        }
        
        public GetUserExpRequest(string username, string password)
        {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserExpResponse", WrapperNamespace="http://microsoft.com/webservices/", IsWrapped=true)]
    public partial class GetUserExpResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://microsoft.com/webservices/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public MizbanWS.expireUser[] GetUserExpResult;
        
        public GetUserExpResponse()
        {
        }
        
        public GetUserExpResponse(MizbanWS.expireUser[] GetUserExpResult)
        {
            this.GetUserExpResult = GetUserExpResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://microsoft.com/webservices/")]
    public partial class GetUserContactResponseGetUserContactResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserContactArray", WrapperNamespace="http://microsoft.com/webservices/", IsWrapped=true)]
    public partial class GetUserContactArrayRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://microsoft.com/webservices/", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://microsoft.com/webservices/", Order=1)]
        public string password;
        
        public GetUserContactArrayRequest()
        {
        }
        
        public GetUserContactArrayRequest(string username, string password)
        {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserContactArrayResponse", WrapperNamespace="http://microsoft.com/webservices/", IsWrapped=true)]
    public partial class GetUserContactArrayResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://microsoft.com/webservices/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public MizbanWS.ContactUser[] GetUserContactArrayResult;
        
        public GetUserContactArrayResponse()
        {
        }
        
        public GetUserContactArrayResponse(MizbanWS.ContactUser[] GetUserContactArrayResult)
        {
            this.GetUserContactArrayResult = GetUserContactArrayResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserNumberArray", WrapperNamespace="http://microsoft.com/webservices/", IsWrapped=true)]
    public partial class GetUserNumberArrayRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://microsoft.com/webservices/", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://microsoft.com/webservices/", Order=1)]
        public string password;
        
        public GetUserNumberArrayRequest()
        {
        }
        
        public GetUserNumberArrayRequest(string username, string password)
        {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserNumberArrayResponse", WrapperNamespace="http://microsoft.com/webservices/", IsWrapped=true)]
    public partial class GetUserNumberArrayResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://microsoft.com/webservices/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public MizbanWS.SeUser[] GetUserNumberArrayResult;
        
        public GetUserNumberArrayResponse()
        {
        }
        
        public GetUserNumberArrayResponse(MizbanWS.SeUser[] GetUserNumberArrayResult)
        {
            this.GetUserNumberArrayResult = GetUserNumberArrayResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetState", WrapperNamespace="http://microsoft.com/webservices/", IsWrapped=true)]
    public partial class GetStateRequest
    {
        
        public GetStateRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStateResponse", WrapperNamespace="http://microsoft.com/webservices/", IsWrapped=true)]
    public partial class GetStateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://microsoft.com/webservices/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public MizbanWS.States[] GetStateResult;
        
        public GetStateResponse()
        {
        }
        
        public GetStateResponse(MizbanWS.States[] GetStateResult)
        {
            this.GetStateResult = GetStateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCities", WrapperNamespace="http://microsoft.com/webservices/", IsWrapped=true)]
    public partial class GetCitiesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://microsoft.com/webservices/", Order=0)]
        public string parent;
        
        public GetCitiesRequest()
        {
        }
        
        public GetCitiesRequest(string parent)
        {
            this.parent = parent;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCitiesResponse", WrapperNamespace="http://microsoft.com/webservices/", IsWrapped=true)]
    public partial class GetCitiesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://microsoft.com/webservices/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public MizbanWS.Cities[] GetCitiesResult;
        
        public GetCitiesResponse()
        {
        }
        
        public GetCitiesResponse(MizbanWS.Cities[] GetCitiesResult)
        {
            this.GetCitiesResult = GetCitiesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllSendSmsArray", WrapperNamespace="http://microsoft.com/webservices/", IsWrapped=true)]
    public partial class GetAllSendSmsArrayRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://microsoft.com/webservices/", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://microsoft.com/webservices/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://microsoft.com/webservices/", Order=2)]
        public int countMsg;
        
        public GetAllSendSmsArrayRequest()
        {
        }
        
        public GetAllSendSmsArrayRequest(string username, string password, int countMsg)
        {
            this.username = username;
            this.password = password;
            this.countMsg = countMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllSendSmsArrayResponse", WrapperNamespace="http://microsoft.com/webservices/", IsWrapped=true)]
    public partial class GetAllSendSmsArrayResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://microsoft.com/webservices/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public MizbanWS.SendMsgUser[] GetAllSendSmsArrayResult;
        
        public GetAllSendSmsArrayResponse()
        {
        }
        
        public GetAllSendSmsArrayResponse(MizbanWS.SendMsgUser[] GetAllSendSmsArrayResult)
        {
            this.GetAllSendSmsArrayResult = GetAllSendSmsArrayResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetVerAndroid", WrapperNamespace="http://microsoft.com/webservices/", IsWrapped=true)]
    public partial class GetVerAndroidRequest
    {
        
        public GetVerAndroidRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetVerAndroidResponse", WrapperNamespace="http://microsoft.com/webservices/", IsWrapped=true)]
    public partial class GetVerAndroidResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://microsoft.com/webservices/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public MizbanWS.VerAndroid[] GetVerAndroidResult;
        
        public GetVerAndroidResponse()
        {
        }
        
        public GetVerAndroidResponse(MizbanWS.VerAndroid[] GetVerAndroidResult)
        {
            this.GetVerAndroidResult = GetVerAndroidResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface WSSMSSoapChannel : MizbanWS.WSSMSSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class WSSMSSoapClient : System.ServiceModel.ClientBase<MizbanWS.WSSMSSoap>, MizbanWS.WSSMSSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WSSMSSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WSSMSSoapClient.GetBindingForEndpoint(endpointConfiguration), WSSMSSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSSMSSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WSSMSSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSSMSSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WSSMSSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSSMSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MizbanWS.GeSMSNumberResponse> MizbanWS.WSSMSSoap.GeSMSNumberAsync(MizbanWS.GeSMSNumberRequest request)
        {
            return base.Channel.GeSMSNumberAsync(request);
        }
        
        public System.Threading.Tasks.Task<MizbanWS.GeSMSNumberResponse> GeSMSNumberAsync(string username, string password)
        {
            MizbanWS.GeSMSNumberRequest inValue = new MizbanWS.GeSMSNumberRequest();
            inValue.username = username;
            inValue.password = password;
            return ((MizbanWS.WSSMSSoap)(this)).GeSMSNumberAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<int> GetMessageStatusAsync(long id)
        {
            return base.Channel.GetMessageStatusAsync(id);
        }
        
        public System.Threading.Tasks.Task<string[]> GetMessageStatuses21Async(long[] id)
        {
            return base.Channel.GetMessageStatuses21Async(id);
        }
        
        public System.Threading.Tasks.Task<string[]> GetMessageStatuses50004Async(long[] id)
        {
            return base.Channel.GetMessageStatuses50004Async(id);
        }
        
        public System.Threading.Tasks.Task<int[]> GetMessageStatusesAsync(long[] id)
        {
            return base.Channel.GetMessageStatusesAsync(id);
        }
        
        public System.Threading.Tasks.Task<string[]> GetPreNumAsync()
        {
            return base.Channel.GetPreNumAsync();
        }
        
        public System.Threading.Tasks.Task<string[]> GetPreNum5000Async()
        {
            return base.Channel.GetPreNum5000Async();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MizbanWS.GetFreeNumResponse> MizbanWS.WSSMSSoap.GetFreeNumAsync(MizbanWS.GetFreeNumRequest request)
        {
            return base.Channel.GetFreeNumAsync(request);
        }
        
        public System.Threading.Tasks.Task<MizbanWS.GetFreeNumResponse> GetFreeNumAsync(string num)
        {
            MizbanWS.GetFreeNumRequest inValue = new MizbanWS.GetFreeNumRequest();
            inValue.num = num;
            return ((MizbanWS.WSSMSSoap)(this)).GetFreeNumAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MizbanWS.GetFreeNum5000Response> MizbanWS.WSSMSSoap.GetFreeNum5000Async(MizbanWS.GetFreeNum5000Request request)
        {
            return base.Channel.GetFreeNum5000Async(request);
        }
        
        public System.Threading.Tasks.Task<MizbanWS.GetFreeNum5000Response> GetFreeNum5000Async(string num)
        {
            MizbanWS.GetFreeNum5000Request inValue = new MizbanWS.GetFreeNum5000Request();
            inValue.num = num;
            return ((MizbanWS.WSSMSSoap)(this)).GetFreeNum5000Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MizbanWS.GePackageResponse> MizbanWS.WSSMSSoap.GePackageAsync(MizbanWS.GePackageRequest request)
        {
            return base.Channel.GePackageAsync(request);
        }
        
        public System.Threading.Tasks.Task<MizbanWS.GePackageResponse> GePackageAsync(string username, string password)
        {
            MizbanWS.GePackageRequest inValue = new MizbanWS.GePackageRequest();
            inValue.username = username;
            inValue.password = password;
            return ((MizbanWS.WSSMSSoap)(this)).GePackageAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<long[]> sendsmsSimCardAsync(string username, string password, string to, string text, string from, string api)
        {
            return base.Channel.sendsmsSimCardAsync(username, password, to, text, from, api);
        }
        
        public System.Threading.Tasks.Task<long[]> sendsms2Async(string username, string password, string to, string text, string from)
        {
            return base.Channel.sendsms2Async(username, password, to, text, from);
        }
        
        public System.Threading.Tasks.Task<long[]> sendsmsAsync(string username, string password, string to, string text, string from, string api)
        {
            return base.Channel.sendsmsAsync(username, password, to, text, from, api);
        }
        
        public System.Threading.Tasks.Task<long[]> DelsendsmsfutureAsync(string username, string password, string Guid)
        {
            return base.Channel.DelsendsmsfutureAsync(username, password, Guid);
        }
        
        public System.Threading.Tasks.Task<long[]> sendsmsfutureAsync(string username, string password, string to, string text, string from, string api, int year, int month, int day, int hour, int min)
        {
            return base.Channel.sendsmsfutureAsync(username, password, to, text, from, api, year, month, day, hour, min);
        }
        
        public System.Threading.Tasks.Task<long[]> NazirSendAsync(string username, string password, string tobank, string text, string from, string api, int year, int month, int day, int hour, int min)
        {
            return base.Channel.NazirSendAsync(username, password, tobank, text, from, api, year, month, day, hour, min);
        }
        
        public System.Threading.Tasks.Task<string> smscounterAsync(string text)
        {
            return base.Channel.smscounterAsync(text);
        }
        
        public System.Threading.Tasks.Task<double> CreditesAsync(string username, string password)
        {
            return base.Channel.CreditesAsync(username, password);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MizbanWS.GetAllMessageArrayResponse> MizbanWS.WSSMSSoap.GetAllMessageArrayAsync(MizbanWS.GetAllMessageArrayRequest request)
        {
            return base.Channel.GetAllMessageArrayAsync(request);
        }
        
        public System.Threading.Tasks.Task<MizbanWS.GetAllMessageArrayResponse> GetAllMessageArrayAsync(string username, string password, int countMsg)
        {
            MizbanWS.GetAllMessageArrayRequest inValue = new MizbanWS.GetAllMessageArrayRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.countMsg = countMsg;
            return ((MizbanWS.WSSMSSoap)(this)).GetAllMessageArrayAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<string> GetBankIdAsync(int bankId)
        {
            return base.Channel.GetBankIdAsync(bankId);
        }
        
        public System.Threading.Tasks.Task<string> GetCountSmsAsync(int bankId, int gender, int receiverNumberKind, int ageStart, int ageEnd, int receiverNumberPrefix)
        {
            return base.Channel.GetCountSmsAsync(bankId, gender, receiverNumberKind, ageStart, ageEnd, receiverNumberPrefix);
        }
        
        public System.Threading.Tasks.Task<string> SendBulkSmsAsync(string username, string password, string api, string from, int bankId, string body, string recordEnd, int gender, int receiverNumberKind, int ageStart, int ageEnd, string title, int receiverNumberPrefix, string recordStart)
        {
            return base.Channel.SendBulkSmsAsync(username, password, api, from, bankId, body, recordEnd, gender, receiverNumberKind, ageStart, ageEnd, title, receiverNumberPrefix, recordStart);
        }
        
        public System.Threading.Tasks.Task<MizbanWS.GetAllMessageResponseGetAllMessageResult> GetAllMessageAsync(string username, string password, int countMsg)
        {
            return base.Channel.GetAllMessageAsync(username, password, countMsg);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MizbanWS.GetUserExpResponse> MizbanWS.WSSMSSoap.GetUserExpAsync(MizbanWS.GetUserExpRequest request)
        {
            return base.Channel.GetUserExpAsync(request);
        }
        
        public System.Threading.Tasks.Task<MizbanWS.GetUserExpResponse> GetUserExpAsync(string username, string password)
        {
            MizbanWS.GetUserExpRequest inValue = new MizbanWS.GetUserExpRequest();
            inValue.username = username;
            inValue.password = password;
            return ((MizbanWS.WSSMSSoap)(this)).GetUserExpAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<MizbanWS.GetUserContactResponseGetUserContactResult> GetUserContactAsync(string username, string password)
        {
            return base.Channel.GetUserContactAsync(username, password);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MizbanWS.GetUserContactArrayResponse> MizbanWS.WSSMSSoap.GetUserContactArrayAsync(MizbanWS.GetUserContactArrayRequest request)
        {
            return base.Channel.GetUserContactArrayAsync(request);
        }
        
        public System.Threading.Tasks.Task<MizbanWS.GetUserContactArrayResponse> GetUserContactArrayAsync(string username, string password)
        {
            MizbanWS.GetUserContactArrayRequest inValue = new MizbanWS.GetUserContactArrayRequest();
            inValue.username = username;
            inValue.password = password;
            return ((MizbanWS.WSSMSSoap)(this)).GetUserContactArrayAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MizbanWS.GetUserNumberArrayResponse> MizbanWS.WSSMSSoap.GetUserNumberArrayAsync(MizbanWS.GetUserNumberArrayRequest request)
        {
            return base.Channel.GetUserNumberArrayAsync(request);
        }
        
        public System.Threading.Tasks.Task<MizbanWS.GetUserNumberArrayResponse> GetUserNumberArrayAsync(string username, string password)
        {
            MizbanWS.GetUserNumberArrayRequest inValue = new MizbanWS.GetUserNumberArrayRequest();
            inValue.username = username;
            inValue.password = password;
            return ((MizbanWS.WSSMSSoap)(this)).GetUserNumberArrayAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<long[]> Logins2Async(string user, string pass)
        {
            return base.Channel.Logins2Async(user, pass);
        }
        
        public System.Threading.Tasks.Task<long[]> LoginsAsync(MizbanWS.NetworkCredential secuity)
        {
            return base.Channel.LoginsAsync(secuity);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MizbanWS.GetStateResponse> MizbanWS.WSSMSSoap.GetStateAsync(MizbanWS.GetStateRequest request)
        {
            return base.Channel.GetStateAsync(request);
        }
        
        public System.Threading.Tasks.Task<MizbanWS.GetStateResponse> GetStateAsync()
        {
            MizbanWS.GetStateRequest inValue = new MizbanWS.GetStateRequest();
            return ((MizbanWS.WSSMSSoap)(this)).GetStateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MizbanWS.GetCitiesResponse> MizbanWS.WSSMSSoap.GetCitiesAsync(MizbanWS.GetCitiesRequest request)
        {
            return base.Channel.GetCitiesAsync(request);
        }
        
        public System.Threading.Tasks.Task<MizbanWS.GetCitiesResponse> GetCitiesAsync(string parent)
        {
            MizbanWS.GetCitiesRequest inValue = new MizbanWS.GetCitiesRequest();
            inValue.parent = parent;
            return ((MizbanWS.WSSMSSoap)(this)).GetCitiesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MizbanWS.GetAllSendSmsArrayResponse> MizbanWS.WSSMSSoap.GetAllSendSmsArrayAsync(MizbanWS.GetAllSendSmsArrayRequest request)
        {
            return base.Channel.GetAllSendSmsArrayAsync(request);
        }
        
        public System.Threading.Tasks.Task<MizbanWS.GetAllSendSmsArrayResponse> GetAllSendSmsArrayAsync(string username, string password, int countMsg)
        {
            MizbanWS.GetAllSendSmsArrayRequest inValue = new MizbanWS.GetAllSendSmsArrayRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.countMsg = countMsg;
            return ((MizbanWS.WSSMSSoap)(this)).GetAllSendSmsArrayAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MizbanWS.GetVerAndroidResponse> MizbanWS.WSSMSSoap.GetVerAndroidAsync(MizbanWS.GetVerAndroidRequest request)
        {
            return base.Channel.GetVerAndroidAsync(request);
        }
        
        public System.Threading.Tasks.Task<MizbanWS.GetVerAndroidResponse> GetVerAndroidAsync()
        {
            MizbanWS.GetVerAndroidRequest inValue = new MizbanWS.GetVerAndroidRequest();
            return ((MizbanWS.WSSMSSoap)(this)).GetVerAndroidAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<long[]> sendsmsGuidAsync(string username, string password, string to, string text, string from, string api, string Guid)
        {
            return base.Channel.sendsmsGuidAsync(username, password, to, text, from, api, Guid);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSSMSSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WSSMSSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSSMSSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://www.my.mizbansms.ir/WsSms.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.WSSMSSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://www.my.mizbansms.ir/WsSms.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WSSMSSoap,
            
            WSSMSSoap12,
        }
    }
}
